package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-provider-istio/istio/internal/helper"
	k8sschema "k8s.io/apimachinery/pkg/runtime/schema"
)

// Compile-time interface checks.
var (
	_ resource.Resource                = &istioCRDResource{}
	_ resource.ResourceWithConfigure   = &istioCRDResource{}
	_ resource.ResourceWithImportState = &istioCRDResource{}
	_ resource.ResourceWithModifyPlan  = &istioCRDResource{}
)

// istioCRDResource is a generic Terraform resource for any Istio CRD.
// All Istio CRDs share the same lifecycle: a single "manifest" JSON attribute
// is passed through to the Kubernetes dynamic client.
type istioCRDResource struct {
	data       *ProviderData
	typeName   string // e.g. "gateway", "virtual_service"
	kind       string // e.g. "Gateway", "VirtualService"
	plural     string // e.g. "gateways", "virtualservices"
	defaultGVR k8sschema.GroupVersionResource
	desc       string
}

// crdModel is the Terraform state model shared by all CRD resources.
type crdModel struct {
	ID       types.String               `tfsdk:"id"`
	Manifest helper.ManifestStringValue `tfsdk:"manifest"`
	Timeouts timeouts.Value             `tfsdk:"timeouts"`
}

// CRDResourceDef defines a single Istio CRD resource for registration.
type CRDResourceDef struct {
	TypeSuffix  string // Terraform resource suffix (e.g. "gateway" → istio_gateway)
	Kind        string // Kubernetes Kind (e.g. "Gateway")
	Plural      string // Kubernetes plural resource name (e.g. "gateways")
	Group       string // API group (e.g. "networking.istio.io")
	Version     string // Default API version (e.g. "v1"); manifest can override
	Description string // Human-readable description for docs
}

// AllCRDResources returns the full set of Istio CRD resource definitions.
func AllCRDResources() []CRDResourceDef {
	return []CRDResourceDef{
		// networking.istio.io
		{TypeSuffix: "gateway", Kind: "Gateway", Plural: "gateways", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio Gateway resource. Gateways configure load balancers at the edge of the mesh for HTTP/TCP ingress traffic."},
		{TypeSuffix: "virtual_service", Kind: "VirtualService", Plural: "virtualservices", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio VirtualService resource. VirtualServices define traffic routing rules for services in the mesh."},
		{TypeSuffix: "destination_rule", Kind: "DestinationRule", Plural: "destinationrules", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio DestinationRule resource. DestinationRules configure traffic policies (load balancing, connection pools, outlier detection, TLS) applied after routing."},
		{TypeSuffix: "service_entry", Kind: "ServiceEntry", Plural: "serviceentries", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio ServiceEntry resource. ServiceEntries add external services or internal services not auto-discovered to the mesh's service registry."},
		{TypeSuffix: "sidecar", Kind: "Sidecar", Plural: "sidecars", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio Sidecar resource. Sidecars fine-tune proxy configuration for specific workloads, controlling what services the sidecar can reach."},
		{TypeSuffix: "envoy_filter", Kind: "EnvoyFilter", Plural: "envoyfilters", Group: "networking.istio.io", Version: "v1alpha3", Description: "Manages an Istio EnvoyFilter resource. EnvoyFilters provide a low-level mechanism to customize the Envoy proxy configuration generated by Istiod."},
		{TypeSuffix: "workload_entry", Kind: "WorkloadEntry", Plural: "workloadentries", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio WorkloadEntry resource. WorkloadEntries describe non-Kubernetes workloads (VMs, bare metal) being onboarded into the mesh."},
		{TypeSuffix: "workload_group", Kind: "WorkloadGroup", Plural: "workloadgroups", Group: "networking.istio.io", Version: "v1", Description: "Manages an Istio WorkloadGroup resource. WorkloadGroups provide a template for a collection of workload instances, similar to how Deployments manage Pods."},
		{TypeSuffix: "proxy_config", Kind: "ProxyConfig", Plural: "proxyconfigs", Group: "networking.istio.io", Version: "v1beta1", Description: "Manages an Istio ProxyConfig resource. ProxyConfigs provide per-workload proxy configuration as a CRD-based alternative to annotations."},
		// security.istio.io
		{TypeSuffix: "peer_authentication", Kind: "PeerAuthentication", Plural: "peerauthentications", Group: "security.istio.io", Version: "v1", Description: "Manages an Istio PeerAuthentication resource. PeerAuthentication controls mutual TLS (mTLS) requirements for inbound connections."},
		{TypeSuffix: "request_authentication", Kind: "RequestAuthentication", Plural: "requestauthentications", Group: "security.istio.io", Version: "v1", Description: "Manages an Istio RequestAuthentication resource. RequestAuthentication defines JWT validation rules for incoming requests."},
		{TypeSuffix: "authorization_policy", Kind: "AuthorizationPolicy", Plural: "authorizationpolicies", Group: "security.istio.io", Version: "v1", Description: "Manages an Istio AuthorizationPolicy resource. AuthorizationPolicies define access control policies (ALLOW, DENY, CUSTOM, AUDIT) for workloads."},
		// telemetry.istio.io
		{TypeSuffix: "telemetry", Kind: "Telemetry", Plural: "telemetries", Group: "telemetry.istio.io", Version: "v1", Description: "Manages an Istio Telemetry resource. Telemetry configures how metrics, traces, and access logs are generated for workloads."},
		// extensions.istio.io
		{TypeSuffix: "wasm_plugin", Kind: "WasmPlugin", Plural: "wasmplugins", Group: "extensions.istio.io", Version: "v1alpha1", Description: "Manages an Istio WasmPlugin resource. WasmPlugins extend Istio proxy functionality via WebAssembly modules."},
	}
}

// NewIstioCRDResource creates a resource.Resource factory for the given CRD definition.
func NewIstioCRDResource(def CRDResourceDef) func() resource.Resource {
	return func() resource.Resource {
		return &istioCRDResource{
			typeName: def.TypeSuffix,
			kind:     def.Kind,
			plural:   def.Plural,
			defaultGVR: k8sschema.GroupVersionResource{
				Group:    def.Group,
				Version:  def.Version,
				Resource: def.Plural,
			},
			desc: def.Description,
		}
	}
}

func (r *istioCRDResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_" + r.typeName
}

func (r *istioCRDResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rschema.Schema{
		Description: r.desc,
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
		Attributes: map[string]rschema.Attribute{
			"id": rschema.StringAttribute{
				Computed:    true,
				Description: "Resource identifier in the format `namespace/name` (or `name` for cluster-scoped resources).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"manifest": rschema.StringAttribute{
				Required:   true,
				CustomType: helper.ManifestStringType{},
				Description: fmt.Sprintf(
					"Full %s manifest as a JSON string. Must include `apiVersion`, `kind`, `metadata.name`, and `metadata.namespace`. "+
						"The `apiVersion` in the manifest determines which API version is used (e.g. `%s/%s` or an older version like `v1beta1`). "+
						"Sensitive fields (tokens, keys, passwords, etc.) are redacted to %q in state after read.",
					r.kind, r.defaultGVR.Group, r.defaultGVR.Version, helper.RedactedPlaceholder,
				),
			},
		},
	}
}

func (r *istioCRDResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *ProviderData, got %T", req.ProviderData))
		return
	}
	r.data = data
}

func (r *istioCRDResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.data == nil || !r.data.ValidateOnPlan {
		return
	}
	var plan, state crdModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !req.State.Raw.IsNull() {
		resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}
	resp.Diagnostics.Append(r.validatePlanDryRun(ctx, plan, state)...)
}

func (r *istioCRDResource) gvrFromStoredManifest(manifestJSON string) k8sschema.GroupVersionResource {
	gvr := r.defaultGVR
	if manifestJSON == "" {
		return gvr
	}
	var m map[string]interface{}
	if err := json.Unmarshal([]byte(manifestJSON), &m); err == nil {
		gvr = helper.GVRFromManifest(r.defaultGVR, m)
	}
	return gvr
}

func (r *istioCRDResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan crdModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := contextWithCreateTimeout(ctx, plan.Timeouts)
	defer cancel()

	manifest, gvr, obj, diags := r.parsePlanManifest(plan.Manifest.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := helper.CreateCRD(ctx, r.data.Dynamic, gvr, obj, false); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Create %s failed", r.kind), err.Error())
		return
	}
	if normalized, err := helper.NormalizeManifestForState(manifest); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Create %s failed", r.kind), err.Error())
		return
	} else {
		plan.Manifest = helper.ManifestStringValue{StringValue: types.StringValue(normalized)}
	}
	plan.ID = types.StringValue(helper.IdFromObject(obj))
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *istioCRDResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state crdModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := contextWithReadTimeout(ctx, state.Timeouts)
	defer cancel()

	gvr := r.gvrFromStoredManifest(state.Manifest.ValueString())
	ns, name := helper.ParseId(state.ID.ValueString())
	obj, err := helper.GetCRD(ctx, r.data.Dynamic, gvr, ns, name)
	if err != nil {
		if helper.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(fmt.Sprintf("Read %s failed", r.kind), err.Error())
		return
	}
	raw, err := helper.ManifestJSONFromObject(obj.Object)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Read %s failed", r.kind), err.Error())
		return
	}
	state.Manifest = helper.ManifestStringValue{StringValue: types.StringValue(raw)}
	state.ID = types.StringValue(helper.IdFromObject(obj))
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *istioCRDResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan crdModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := contextWithUpdateTimeout(ctx, plan.Timeouts)
	defer cancel()

	manifest, gvr, obj, diags := r.parsePlanManifest(plan.Manifest.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := helper.UpdateCRD(ctx, r.data.Dynamic, gvr, obj, false); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Update %s failed", r.kind), err.Error())
		return
	}
	if normalized, err := helper.NormalizeManifestForState(manifest); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Update %s failed", r.kind), err.Error())
		return
	} else {
		plan.Manifest = helper.ManifestStringValue{StringValue: types.StringValue(normalized)}
	}
	plan.ID = types.StringValue(helper.IdFromObject(obj))
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *istioCRDResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state crdModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := contextWithDeleteTimeout(ctx, state.Timeouts)
	defer cancel()

	gvr := r.gvrFromStoredManifest(state.Manifest.ValueString())
	ns, name := helper.ParseId(state.ID.ValueString())
	if err := helper.DeleteCRD(ctx, r.data.Dynamic, gvr, ns, name); err != nil && !helper.IsNotFound(err) {
		resp.Diagnostics.AddError(fmt.Sprintf("Delete %s failed", r.kind), err.Error())
	}
}

// ImportState supports `terraform import istio_<type>.<name> <namespace>/<resource-name>`.
func (r *istioCRDResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
